In [8]:
import torch
import numpy as np

VECTOR

In [10]:
x = torch.tensor([1, 2, 3])
x[0]

tensor(1)

In [11]:
x.shape[0]

3

In [12]:
x[x.shape[0] - 1]

tensor(3)

In [13]:
x[-1]

tensor(3)

In [14]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7])

In [15]:
x[::2]

tensor([1, 3, 5, 7])

MATRIX


In [16]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [17]:
A[2, 1]

tensor(6)

In [19]:
float(A[2, 1])

6.0

In [20]:
A[1:, :1]

tensor([[3],
        [5]])

In [21]:
A[:, 1]

tensor([2, 4, 6])

DTYPE

In [22]:
points = torch.tensor([7, 8, 10, 6.5])
points.dtype

torch.float32

In [23]:
points = torch.tensor([7, 8, 10, 6])
points.dtype

torch.int64

In [24]:
points = torch.tensor([7, 8, 10, 6], dtype = torch.short)
points.dtype

torch.int16

In [25]:
points = torch.tensor([7, 8, 10, 6]).short()
points.dtype

torch.int16

TRANSPOSE

In [26]:
A = torch.tensor([[1, 2], [3, 4], [5, 6]])
A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [27]:
A_t = A.transpose(0, 1)
A_t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [28]:
A.shape, A_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [32]:
A = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
A

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [33]:
A.shape

torch.Size([2, 3, 4])

In [34]:
A_t = A.transpose(0, 1)
A_t

tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])

In [35]:
A_t.shape

torch.Size([3, 2, 4])

Storage

In [37]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.storage()

C:\Users\Admin\AppData\Local\Temp\ipykernel_13448\264782167.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage()


 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [38]:
x[1][2] == x.storage()[5]

tensor(True)

TENSOR METADATA: size, offset, stride

In [39]:
x = torch.tensor([[3, 1, 2], [4, 1, 7]])
x_t = x.t()
id(x.storage()) == id(x_t.storage())

True

In [40]:
x.stride(), x_t.stride()

((3, 1), (1, 3))

CONTIGUOUS TENSORS

In [41]:
x.is_contiguous()

True

In [42]:
x_t.is_contiguous()

False

In [44]:
x_t_con = x_t.contiguous()
x_t_con

tensor([[3, 4],
        [1, 1],
        [2, 7]])

In [45]:
x_t_con.storage()

 3
 4
 1
 1
 2
 7
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

TORCH GPU

In [1]:
x_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
x_gpu

NameError: name 'torch' is not defined

TORCH TO NUMPY

In [49]:
x = torch.tensor([1, 2, 3])
x_np = x.numpy()
x_np

array([1, 2, 3], dtype=int64)

In [50]:
x[1] = 0
x, x_np

(tensor([1, 0, 3]), array([1, 0, 3], dtype=int64))